/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package win7calcclone;

import java.awt.Font;

/**
 *
 * @author ReaLgressA
 */
public class MainWindow extends javax.swing.JFrame {
    private NumberStorage numStorage;
    
    public MainWindow(NumberStorage numStorage) {
        this.numStorage = numStorage;
        initComponents();
        getContentPane().setBackground(getBackground());
        UpdateDisplay();
    }
    
    public final void UpdateDisplay() {
        String displayNumber = numStorage.GetDisplayNumber();
        if(displayNumber.length() > 12) {
            jLabelNumber.setFont(new Font("Serif", Font.PLAIN, 18));
        } else {
            jLabelNumber.setFont(new Font("Serif", Font.PLAIN, 22));
        }
        jLabelNumber.setText(displayNumber);
        jLabelMemory.setText(numStorage.HasValueInMemory() ? "M" : "");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCalc = new javax.swing.JPanel();
        jLabelExpression = new javax.swing.JLabel();
        jLabelNumber = new javax.swing.JLabel();
        jLabelMemory = new javax.swing.JLabel();
        jButtonMR = new javax.swing.JButton();
        jButtonMC = new javax.swing.JButton();
        jButtonMS = new javax.swing.JButton();
        jButtonMPlus = new javax.swing.JButton();
        jButtonMMinus = new javax.swing.JButton();
        jButtonBackspace = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum0 = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonC = new javax.swing.JButton();
        jButtonCE = new javax.swing.JButton();
        jButtonSquareRoot = new javax.swing.JButton();
        jButtonInvertSign = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButtonDivision = new javax.swing.JButton();
        jButtonPercent = new javax.swing.JButton();
        jButtonMultiplication = new javax.swing.JButton();
        jButtonReciprocating = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonCalculate = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator");
        setBackground(new java.awt.Color(220, 237, 255));
        setMaximumSize(new java.awt.Dimension(220, 320));
        setMinimumSize(new java.awt.Dimension(220, 320));
        setPreferredSize(new java.awt.Dimension(220, 320));
        setResizable(false);
        setSize(new java.awt.Dimension(220, 320));

        jPanelCalc.setBackground(new java.awt.Color(240, 248, 255));
        jPanelCalc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelExpression.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        jLabelExpression.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelExpression.setText("12345_____12345_____12345_____ ");
        jLabelExpression.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabelExpression.setMaximumSize(new java.awt.Dimension(45, 15));
        jLabelExpression.setMinimumSize(new java.awt.Dimension(45, 15));
        jLabelExpression.setPreferredSize(new java.awt.Dimension(45, 15));

        jLabelNumber.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabelNumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelNumber.setText("3072");
        jLabelNumber.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jLabelMemory.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabelMemory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMemory.setText("M");
        jLabelMemory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMemory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanelCalcLayout = new javax.swing.GroupLayout(jPanelCalc);
        jPanelCalc.setLayout(jPanelCalcLayout);
        jPanelCalcLayout.setHorizontalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addComponent(jLabelMemory, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelExpression, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelCalcLayout.setVerticalGroup(
            jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCalcLayout.createSequentialGroup()
                .addComponent(jLabelExpression, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCalcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMemory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jButtonMR.setBackground(new java.awt.Color(169, 198, 255));
        jButtonMR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonMR.setText("MR");
        jButtonMR.setBorder(null);
        jButtonMR.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMR.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMR.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMRActionPerformed(evt);
            }
        });

        jButtonMC.setBackground(new java.awt.Color(169, 198, 255));
        jButtonMC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonMC.setText("MC");
        jButtonMC.setBorder(null);
        jButtonMC.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMC.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMC.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMCActionPerformed(evt);
            }
        });

        jButtonMS.setBackground(new java.awt.Color(169, 198, 255));
        jButtonMS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonMS.setText("MS");
        jButtonMS.setBorder(null);
        jButtonMS.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMS.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMS.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMSActionPerformed(evt);
            }
        });

        jButtonMPlus.setBackground(new java.awt.Color(169, 198, 255));
        jButtonMPlus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonMPlus.setText("M+");
        jButtonMPlus.setBorder(null);
        jButtonMPlus.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMPlus.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMPlus.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMPlusActionPerformed(evt);
            }
        });

        jButtonMMinus.setBackground(new java.awt.Color(169, 198, 255));
        jButtonMMinus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonMMinus.setText("M-");
        jButtonMMinus.setBorder(null);
        jButtonMMinus.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMMinus.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMMinus.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMMinusActionPerformed(evt);
            }
        });

        jButtonBackspace.setBackground(new java.awt.Color(180, 214, 249));
        jButtonBackspace.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jButtonBackspace.setText("←");
        jButtonBackspace.setAutoscrolls(true);
        jButtonBackspace.setBorder(null);
        jButtonBackspace.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonBackspace.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonBackspace.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonBackspace.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButtonBackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackspaceActionPerformed(evt);
            }
        });

        jButtonNum7.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum7.setText("7");
        jButtonNum7.setBorder(null);
        jButtonNum7.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum7.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum7.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum7ActionPerformed(evt);
            }
        });

        jButtonNum1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum1.setText("1");
        jButtonNum1.setBorder(null);
        jButtonNum1.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum1.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum1.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });

        jButtonNum4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum4.setText("4");
        jButtonNum4.setBorder(null);
        jButtonNum4.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum4.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum4.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum4ActionPerformed(evt);
            }
        });

        jButtonNum0.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum0.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum0.setText("0");
        jButtonNum0.setBorder(null);
        jButtonNum0.setMaximumSize(new java.awt.Dimension(70, 27));
        jButtonNum0.setMinimumSize(new java.awt.Dimension(70, 27));
        jButtonNum0.setPreferredSize(new java.awt.Dimension(70, 27));
        jButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum0ActionPerformed(evt);
            }
        });

        jButtonNum2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum2.setText("2");
        jButtonNum2.setBorder(null);
        jButtonNum2.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum2.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum2.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });

        jButtonNum5.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum5.setText("5");
        jButtonNum5.setBorder(null);
        jButtonNum5.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum5.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum5.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum5ActionPerformed(evt);
            }
        });

        jButtonNum8.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum8.setText("8");
        jButtonNum8.setBorder(null);
        jButtonNum8.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum8.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum8.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum8ActionPerformed(evt);
            }
        });

        jButtonNum3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum3.setText("3");
        jButtonNum3.setBorder(null);
        jButtonNum3.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum3.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum3.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });

        jButtonNum6.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum6.setText("6");
        jButtonNum6.setBorder(null);
        jButtonNum6.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum6.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum6.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum6ActionPerformed(evt);
            }
        });

        jButtonNum9.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNum9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonNum9.setText("9");
        jButtonNum9.setBorder(null);
        jButtonNum9.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonNum9.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonNum9.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum9ActionPerformed(evt);
            }
        });

        jButtonC.setBackground(new java.awt.Color(180, 214, 249));
        jButtonC.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonC.setText("C");
        jButtonC.setAutoscrolls(true);
        jButtonC.setBorder(null);
        jButtonC.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonC.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonC.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCActionPerformed(evt);
            }
        });

        jButtonCE.setBackground(new java.awt.Color(180, 214, 249));
        jButtonCE.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButtonCE.setText("CE");
        jButtonCE.setAutoscrolls(true);
        jButtonCE.setBorder(null);
        jButtonCE.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonCE.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonCE.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCEActionPerformed(evt);
            }
        });

        jButtonSquareRoot.setBackground(new java.awt.Color(180, 214, 249));
        jButtonSquareRoot.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonSquareRoot.setText("√");
        jButtonSquareRoot.setAutoscrolls(true);
        jButtonSquareRoot.setBorder(null);
        jButtonSquareRoot.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonSquareRoot.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonSquareRoot.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonInvertSign.setBackground(new java.awt.Color(180, 214, 249));
        jButtonInvertSign.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonInvertSign.setText("±");
        jButtonInvertSign.setAutoscrolls(true);
        jButtonInvertSign.setBorder(null);
        jButtonInvertSign.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonInvertSign.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonInvertSign.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonPoint.setBackground(new java.awt.Color(255, 255, 255));
        jButtonPoint.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButtonPoint.setText(".");
        jButtonPoint.setBorder(null);
        jButtonPoint.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonPoint.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonPoint.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jButtonDivision.setBackground(new java.awt.Color(180, 214, 249));
        jButtonDivision.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonDivision.setText("/");
        jButtonDivision.setAutoscrolls(true);
        jButtonDivision.setBorder(null);
        jButtonDivision.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonDivision.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonDivision.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonPercent.setBackground(new java.awt.Color(180, 214, 249));
        jButtonPercent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPercent.setText("%");
        jButtonPercent.setAutoscrolls(true);
        jButtonPercent.setBorder(null);
        jButtonPercent.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonPercent.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonPercent.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonMultiplication.setBackground(new java.awt.Color(180, 214, 249));
        jButtonMultiplication.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonMultiplication.setText("*");
        jButtonMultiplication.setAutoscrolls(true);
        jButtonMultiplication.setBorder(null);
        jButtonMultiplication.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMultiplication.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMultiplication.setPreferredSize(new java.awt.Dimension(33, 27));
        jButtonMultiplication.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        jButtonReciprocating.setBackground(new java.awt.Color(180, 214, 249));
        jButtonReciprocating.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonReciprocating.setText("<html>1/<i>x</i></html>");
        jButtonReciprocating.setAutoscrolls(true);
        jButtonReciprocating.setBorder(null);
        jButtonReciprocating.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonReciprocating.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonReciprocating.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonMinus.setBackground(new java.awt.Color(180, 214, 249));
        jButtonMinus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonMinus.setText("-");
        jButtonMinus.setAutoscrolls(true);
        jButtonMinus.setBorder(null);
        jButtonMinus.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonMinus.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonMinus.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonPlus.setBackground(new java.awt.Color(180, 214, 249));
        jButtonPlus.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButtonPlus.setText("+");
        jButtonPlus.setAutoscrolls(true);
        jButtonPlus.setBorder(null);
        jButtonPlus.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonPlus.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonPlus.setPreferredSize(new java.awt.Dimension(33, 27));

        jButtonCalculate.setBackground(new java.awt.Color(180, 214, 249));
        jButtonCalculate.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jButtonCalculate.setText("=");
        jButtonCalculate.setAutoscrolls(true);
        jButtonCalculate.setBorder(null);
        jButtonCalculate.setMaximumSize(new java.awt.Dimension(33, 27));
        jButtonCalculate.setMinimumSize(new java.awt.Dimension(33, 27));
        jButtonCalculate.setPreferredSize(new java.awt.Dimension(33, 27));

        jMenu1.setText("View");
        jMenuBar.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar.add(jMenu3);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonInvertSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonNum0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonReciprocating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 21, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonMC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBackspace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonCE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonInvertSign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSquareRoot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButtonNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonMultiplication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonReciprocating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        numStorage.AddSymbol('1');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        numStorage.AddSymbol('2');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        numStorage.AddSymbol('3');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum4ActionPerformed
        numStorage.AddSymbol('4');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum4ActionPerformed

    private void jButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum5ActionPerformed
        numStorage.AddSymbol('5');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum5ActionPerformed

    private void jButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum6ActionPerformed
        numStorage.AddSymbol('6');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum6ActionPerformed

    private void jButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum7ActionPerformed
        numStorage.AddSymbol('7');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum7ActionPerformed

    private void jButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum8ActionPerformed
        numStorage.AddSymbol('8');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum8ActionPerformed

    private void jButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum9ActionPerformed
        numStorage.AddSymbol('9');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum9ActionPerformed

    private void jButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum0ActionPerformed
        numStorage.AddSymbol('0');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonNum0ActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        numStorage.AddSymbol('.');
        UpdateDisplay();
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButtonBackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackspaceActionPerformed
        numStorage.Backspace();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonBackspaceActionPerformed

    private void jButtonCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCEActionPerformed
        numStorage.ClearEntry();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonCEActionPerformed

    private void jButtonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCActionPerformed
        numStorage.Clear();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonCActionPerformed

    private void jButtonMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMCActionPerformed
        numStorage.MemoryClear();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonMCActionPerformed

    private void jButtonMRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMRActionPerformed
        numStorage.MemoryRecall();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonMRActionPerformed

    private void jButtonMSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMSActionPerformed
        numStorage.MemoryStore();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonMSActionPerformed

    private void jButtonMPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMPlusActionPerformed
        numStorage.MemoryAdd();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonMPlusActionPerformed

    private void jButtonMMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMMinusActionPerformed
        numStorage.MemorySubtract();
        UpdateDisplay();
    }//GEN-LAST:event_jButtonMMinusActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackspace;
    private javax.swing.JButton jButtonC;
    private javax.swing.JButton jButtonCE;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JButton jButtonDivision;
    private javax.swing.JButton jButtonInvertSign;
    private javax.swing.JButton jButtonMC;
    private javax.swing.JButton jButtonMMinus;
    private javax.swing.JButton jButtonMPlus;
    private javax.swing.JButton jButtonMR;
    private javax.swing.JButton jButtonMS;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMultiplication;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonPercent;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JButton jButtonReciprocating;
    private javax.swing.JButton jButtonSquareRoot;
    private javax.swing.JLabel jLabelExpression;
    private javax.swing.JLabel jLabelMemory;
    private javax.swing.JLabel jLabelNumber;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanelCalc;
    // End of variables declaration//GEN-END:variables
}
